package com.chomugiri.app.core

import android.content.Context
import android.net.Uri
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Writes the artifact out as a real .zip to wherever the user picked via the system file picker.
 * No storage permission is involved — the Storage Access Framework hands us the stream directly.
 */
fun writeArtifactZip(context: Context, uri: Uri, artifact: Artifact): Int {
    var written = 0
    context.contentResolver.openOutputStream(uri)?.use { out ->
        ZipOutputStream(out.buffered()).use { zip ->
            for (f in artifact.files) {
                val safePath = f.path.trimStart('/').replace("..", "_")
                if (safePath.isBlank()) continue
                zip.putNextEntry(ZipEntry(safePath))
                zip.write(f.content.toByteArray(Charsets.UTF_8))
                zip.closeEntry()
                written++
            }
            zip.putNextEntry(ZipEntry("README.txt"))
            zip.write(
                """
                ${artifact.title}
                Generated by ChomuGirI.

                ${artifact.files.size} file(s):
                ${artifact.files.joinToString("\n") { "  - " + it.path }}
                """.trimIndent().toByteArray(Charsets.UTF_8)
            )
            zip.closeEntry()
        }
    } ?: throw IllegalStateException("Couldn't open that location for writing.")
    return written
}

fun suggestedZipName(artifact: Artifact): String {
    val base = artifact.title
        .lowercase()
        .replace(Regex("[^a-z0-9]+"), "-")
        .trim('-')
        .take(40)
        .ifBlank { "chomugiri-project" }
    return "$base.zip"
}
